baseURL = 'https://db.nihds.com/'
languageCode = 'zh-cn'
title = '数据库原理'
theme = 'ananke'

resourceDir = "./resources"

DefaultContentLanguage = "zh"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.zh]
    title = "数据库原理"
    weight = 1
    contentDir = "content/zh"
    # languageDirection = 'rtl' for Right-To-Left languages


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 10
